// <auto-generated />
using BackForVue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackForVue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230706045401_hello")]
    partial class hello
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackForVue.Models.Employe", b =>
                {
                    b.Property<int>("NumEmp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<int>("Salaire")
                        .HasColumnType("int");

                    b.HasKey("NumEmp");

                    b.ToTable("Employes");
                });
#pragma warning restore 612, 618
        }
    }
}
